### ISSUE TITLE
Investigate Tox for Automated Testing

### ISSUE THREAD

**Issue by mikelor** [mikelor/FlyWhy#8]
The CookieCutter Data Science template sets up a Tox.ini file. [Tox](https://tox.readthedocs.io/en/latest/) aims to automate and standardize testing in Python. It is part of a larger vision of easing the packaging, testing and release process of Python software.

This looks like it could be valuable, if it is, setup Tox, if not delete the Tox.ini file

**Comment by mikelor** [comment]
Not sure it's worth the effort to learn / use Tox at the moment.  When running Tox, I was unable to successfully complete the command w/o erroring
```
(flywhy) C:\Users\mikel\repos\FlyWhy>tox
GLOB sdist-make: C:\Users\mikel\repos\FlyWhy\setup.py
py38 create: C:\Users\mikel\repos\FlyWhy\.tox\py38
py38 installdeps: pytest
py38 inst: C:\Users\mikel\repos\FlyWhy\.tox\.tmp\package\1\src-0.1.0.zip
_______________________________________________________ summary _______________________________________________________
  py38: commands succeeded
  congratulations :)
Traceback (most recent call last):
  File "C:\Users\mikel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\py\_error.py", line 66, in checked_call
    return func(*args, **kwargs)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\mikel\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\python.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
```
